### PR TITLE
lib/ template

### PR DESCRIPTION
**Pull request by wwood**
Hey dude - pull request as I eluded to to in the email. I actually wasn't able to get this to work without adding 
require 'rubygems'
to the biogem executable, if that matters to you.

### CODE REVIEW

**Comment by rjpbonnal** [comment]
I'm going to accept your pull.
About rubygems, are you using Ruby 1.9 ?

**Comment by wwood** [comment]
no, I wasn't using ruby1.9. That would make sense then. Are you planning on being 1.8 compatible?

**Comment by rjpbonnal** [comment]
With ruby 1.8.x you must require rubygems explicitly, which is not required on ruby 1.9.
About supporting ruby 1.8, I'd like to support just 1.9 but if there are a lot of request on 1.8 I could consider.
Actually we can add the require it's not so cute but it would work in both cases

**Comment by wwood** [comment]
Argh. I was just reading a somewhat violent fantasy book on my cheapo ebook reader, when I drop it and it slices my chin open. Reading made me bleed.

As far as I can tell the it seems to work fine on 1.8 otherwise, but since there doesn't seem to be any tests in biogem yet I can't be too certain of that. That's a nagging comment to make I know..

**Comment by rjpbonnal** [comment]
"That's a nagging comment to make I know.."
My English is not so advanced, dude :-)
Come to BOSC and to Codefest it's just 2 days before, and we could work together, it's a very useful event !

**Pull request merged**
